import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavigationEvents from '../components/NavigationEvents';
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
        </body>
    </html>
  )
}
